### ISSUE TITLE
The app says I have no connection while I’m at full 4G

### ISSUE THREAD

**Issue by codedbypm** [minvws/nl-covid19-coronacheck-app-ios#32] opened 2021-06-18 17:24 UTC
### Describe the bug, issue or concern

Just installed and opened the app, and it keeps spinning saying "we'r starting the app". And after some seconds it tells me I'm not connected to the internet

### Expected behavior
I would expect the app to handle better the check over connectivity. 

### Screenshots
![image](https://user-images.githubusercontent.com/17159280/122596688-8a47bc80-d06a-11eb-91d9-c8a88278b115.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: 14.6
 - Version 1.4

### Additional context
I opened the app while being in Italy.

### Governance
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by iandundas** [comment] 2021-06-28 12:15
Thanks for the report @codedbypm 

We think this was probably caused by a server being busy, would you mind retrying just so we can be sure that the app works for you now?

We are currently working on improving the errors that are displayed in such situations

Thanks!

**Comment by iandundas** [comment] 2021-07-21 08:20
Closing for now.

**Closed by iandundas** 2021-07-21 08:20 UTC
