### ISSUE TITLE
Certificate time uses clientside date validation

### ISSUE THREAD

**Issue by godwindejong** [minvws/nl-covid19-coronacheck-app-ios#48] opened 2021-07-30 13:16 UTC
Dear developers,

It has come to my attention that the Corona check app uses client side date validation. This seems to be an oversight!

Use case:
I have my second shot, on July 30th, the app recognizes this and tells met it will be 13 days until my Dutch certificate becomes valid. I change my local phone time to 15th of August, and voila, the app displays a (valid?) code.

Please fix.

**Comment by iandundas** [comment] 2021-07-30 17:49
Sure, but the QR code won’t be accepted by the [scanner app](https://apps.apple.com/nl/app/scanner-for-coronacheck/id1549842661?l=en).

**Comment by iandundas** [comment] 2021-07-30 17:51
Apologies for closing the issue, feel free to respond and I can explain further :)

**Comment by godwindejong** [comment] 2021-08-02 06:27
Good to know this is not really a problem, still might be better to use server time for validation.

**Comment by Rool** [comment] 2021-08-02 07:04
One of the premises of the app is to use your QR offline. We do not want to do any network calls when displaying the QR:

- Privacy, we do not track where and when you show the QR
- Location, you might have a very poor network in a remote venue (i.e. Lowlands)

What we will do in a future / next version:
- try to detect clock skew when doing any network calls to the CoronaCheck backend.
- display a warning.

There will be loopholes. It is hard to detect clock skew if you are offline. (start the app, retrieve the config, change your clock, show the qr)

**Comment by sander3** [comment] 2021-08-04 15:34
https://github.com/instacart/TrueTime.swift

**Comment by ijansch** [comment] 2021-08-10 10:18
Sine the original issue (the fact that you can forward in time and make the qr visible) is intended behaviour, I'll close the issue for now. As mentioned above: the validation is done on the date inside the QR, which is digitally signed.

**Closed by ijansch** 2021-08-10 10:18 UTC
