### ISSUE TITLE
Integrate with Apple Wallet

### ISSUE THREAD

**Issue by CasEbbers** [minvws/nl-covid19-coronacheck-app-ios#82] opened 2021-11-08 16:56 UTC
Implementation of the PassKit API to add your QR to Apple Wallet would be a great addition.

**Comment by michaeldeborst** [comment] 2021-12-19 11:20
Yes please! Now that we have to show the code more often it would be great to be able to have it integrated in wallet and visible through Apple Watch. Austria's green pass app has this implemented already. Apple has some documentation here for the feature. https://developer.apple.com/videos/play/wwdc2021/10089/

**Comment by nicktencate** [comment] 2021-12-20 09:23
Duplicate of https://github.com/minvws/nl-covid19-coronacheck-app-coordination/issues/48

**Closed by nicktencate** 2021-12-20 09:23 UTC
